### ISSUE TITLE
InputText

### ISSUE THREAD

**Issue by VaclavSir** [kiwicom/react-kiwi-ui#19]
- Rename Input to InputText
- Fixes to the design:
  - When the value is empty, the label has different color
  - When there is an error, the input has different border color

See https://app.zeplin.io/project/5a859818a44a3c0f897647b1/dashboard?q=text%20basic
![screen shot 2018-02-22 at 16 03 08](https://user-images.githubusercontent.com/1473642/36545743-e6e5cfdc-17e9-11e8-8923-5fc9ed573a53.png)

**Comment by oreqizer** [comment]
we should have a generic `Input` component, with variations of specific needs as separate ones:
* `InputText`
* `InputNumber`
...etc

**Comment by jakubzaba** [comment]
General Input issue #24.
