### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/react-kiwi-ui#29]
https://app.zeplin.io/project/5a85990b663b8b462f03ca55

Props:

- [x] sizes (large | normal | small)

- [x] type (secondary | primary )

- [x] Icon (withIcon | without Icon)

- [x] disabled | enabled 

![screen shot 2018-02-26 at 14 59 12](https://user-images.githubusercontent.com/6354326/36674211-b5e587c8-1b05-11e8-845c-f68ded6ac3b0.png)

**Comment by Fallion** [comment]
Closed by #49
